### ISSUE TITLE
login typo color from black to white

### ISSUE THREAD

**Issue by Mordhin** [Mordhin/starships-looters#113]
![image](https://user-images.githubusercontent.com/68302860/100344288-e2d93e80-2fe0-11eb-8612-ea1af4ba4d52.png)

**Comment by sbriclot** [comment]
Maybe we can put the background of the container in white ?
![image](https://user-images.githubusercontent.com/70663477/100356594-ba0e7480-2ff3-11eb-8aa3-5bd562c39e50.png)

**Comment by adcousin** [comment]
Not necessary after background color change
