### ISSUE TITLE
Add a favicon in layout.html.erb

### ISSUE THREAD

**Issue by adcousin** [Mordhin/starships-looters#16]
- [ ] Choose a favicon
- [ ] Update assets/img
- [ ] Update layout.html.erb

[(https://medium.com/@josephcardillo/how-to-add-a-favicon-to-your-rails-app-9676336f7006)]

**Comment by sbriclot** [comment]
Favicon suggestion
https://digitalyse.fr/wp-content/uploads/2019/06/favicon-digitalyse.png
