### ISSUE TITLE
Customize navbar

### ISSUE THREAD

**Issue by adcousin** [Mordhin/starships-looters#18]
- [ ] Choose a logo
- [ ] Upload logo to assets
- [ ] Implement in navbar

**Comment by JPS09** [comment]
Logos
https://www.flaticon.com/free-icon/spaceship_3538041?term=spaceship&page=2&position=19
https://www.flaticon.com/free-icon/spaceship_749470?term=spaceship&page=2&position=40
https://www.flaticon.com/free-icon/rocket_1168593?term=spaceship&page=3&position=79
https://www.flaticon.com/free-icon/spacecraft_1033040?term=spaceship&page=1&position=33

Some logos to see (SVG when dowloading)

**Comment by adcousin** [comment]
J'ai voté sur le post de JP

**Comment by JPS09** [comment]
Rechoisir un logo qui correspond à la charte graphique
