### ISSUE TITLE
bookings_new

### ISSUE THREAD

**Issue by JPS09** [Mordhin/starships-looters#61]
- [x] Add ship name
- [x] Add ship photo
- [x] Add ship owner
- [x] Add price
- [x] Add cancel button to form

**Comment by JPS09** [comment]
Crer method is_booked? qui renvoei true ou false si booké
Prend en paramètre une date, tu regardes si ça chevauches une autre date

**Comment by adcousin** [comment]
Je crois que la set_params est broken, c'est `require(:booking)` au lieu de `require(:bookings)` peut-être ?
![booking_controller_create_issue](https://user-images.githubusercontent.com/72085355/100214392-2152f880-2f10-11eb-81f3-7d1ac567eb3c.png)

**Comment by JPS09** [comment]
- [ ] Modify crew size into Attendents
