### ISSUE TITLE
Talk about the graphical charter

### ISSUE THREAD

**Issue by JPS09** [Mordhin/starships-looters#98]
Based on @Mordhin idea:

- [x] Main colors > Julien
- [x] Main picture on homepage (https://4kwallpaper.wiki/wp-content/uploads/2019/07/195451.jpg) > Julien
- [x] Fonts > Julien
- [x] Style (shadow, border-radius, gradient...) > Julien
- [x] Logo > JP
- [x] Avatar/Badge for users > Nobod'
- [x] Buttons (form, search, actions, status) > Julien
- [x] Links icons (back, add ,edit, delete) > JP
- [x] card-product (par exemple pour avoir une vue compacte de tous les bookings un peu comme dans le site des skills de Louise) > Adrien
- [x] Other icons or colors codes (category, origin universe, purpose) > JP

**Comment by JPS09** [comment]
- [https://spacenews.com/wp-content/uploads/2018/05/24359364107_152b0152ff_k.jpg](url)
- https://wallpaperaccess.com/space-art-hd
- https://upload.wikimedia.org/wikipedia/commons/6/6a/Pillars_of_Creation.jpeg
- https://www.arsastronautica.com/images/sos-1.jpg
- https://cdna.artstation.com/p/assets/images/images/007/314/080/large/daedalus-system-vcokjblr6vm-1.jpg?1505263556
- https://cristianodalbem.com/static/a6c7279e47148358b09d49a3b96ad2a6/2a8be/space5.jpg
- https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.lefthudson.com%2Ffantasy-space-wallpaper%2Ffantasy-space-wallpaper-elegant-space-fantasy-wallpaper-set-59-awesome-wallpapers-for-you%2F&psig=AOvVaw2nar0aFeSNrfv1F6gSvaB3&ust=1606469346222000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLDJ9fLyn-0CFQAAAAAdAAAAABAL
- https://dribbble.com/JPSYMOENS/collections/3981047-Spacelooters?utm_source=Clipboard_clipboard_collection&utm_campaign=JPSYMOENS&utm_content=Spacelooters&utm_medium=Social_Share
- https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F358739926565601447%2F&psig=AOvVaw2nar0aFeSNrfv1F6gSvaB3&ust=1606469346222000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLDJ9fLyn-0CFQAAAAAdAAAAABAS
- https://www.google.com/url?sa=i&url=https%3A%2F%2Ffree4kwallpapers.com%2Ffantasy%2Fspace-fantasy-wallpaper--q21R&psig=AOvVaw2nar0aFeSNrfv1F6gSvaB3&ust=1606469346222000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLDJ9fLyn-0CFQAAAAAdAAAAABAY
- https://image.cnbcfm.com/api/v1/image/106334257-1578946243766jcsat-18spacex.jpg?v=1578946334
- https://www.99images.com/photos/wallpapers/space/space-fantasyandroid-iphone-desktop-hd-backgrounds-wallpapers-1080p-4k-xhr4s.jpg?v=1584589445

**Comment by Mordhin** [comment]
14. https://i.imgur.com/mQtOWnl.jpeg

**Comment by JPS09** [comment]
- [ ] 6
- [ ] 8
- [ ] 12

**Comment by adcousin** [comment]
Fonts
#### Google fonts
##### Orbitron
`@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;600;900&display=swap');`
`font-family: 'Orbitron', sans-serif;`

**Comment by adcousin** [comment]
### Style
Modifiez les variables bootstrap dans `app/assets/stylesheets/config/`

#### Border-radius
`$border-radius: 3px;`
`$border-color; ...;`

**Comment by JPS09** [comment]
Website delivered
